services:
  auth-service:
    build: 
     context: ../Authentication-Service
     dockerfile: ./Dockerfile
    ports:
      - "5000:8080"
    env_file: .env
    environment:
      - Jwt__Key=${Jwt__Key}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__AuthDb}
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMq__Host=rabbitmq
    depends_on:
      - auth-db
      - rabbitmq

  user-service:
    build: 
     context: ../User-Service
     dockerfile: ./Dockerfile
    ports:
      - "5001:8080"
    env_file: .env
    environment:
      - Jwt__Key=${Jwt__Key}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__UserDb}
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMq__Host=rabbitmq
    depends_on:
      - user-db
      - rabbitmq

  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  user-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
     SA_PASSWORD: ${DB_PASSWORD}
     ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RabbitMq__User}
      - RABBITMQ_DEFAULT_PASS=${RabbitMq__Password}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  chat-service:
    build:
      context: ../Chat-Service
      dockerfile: ./Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - mongo-db
    env_file: .env
    environment:
      - Jwt__Key=${Jwt__Key}
      - MongoDb__ConnectionString=mongodb://mongo-db:27017
      - MongoDb__Database=ChatApp
      - ASPNETCORE_ENVIRONMENT=Production

  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ../Messaging-Application-FE/messaging-app
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"  
    depends_on:
      - auth-service
      - user-service
      - chat-service
      - media-service

  media-service:
    build:
      context: ../Media-Service
      dockerfile: ./Dockerfile
    ports:
      - "5003:8080"
    env_file: .env
    environment:
      - AzureBlob__ConnectionString=${AzureBlob__ConnectionString}
      - AzureBlob__ContainerName=media
      - Jwt__Key=${Jwt__Key}
volumes:
  rabbitmq_data:
  mongo_data:



